### ISSUE TITLE
Add a new clan

### ISSUE THREAD

**Issue by Rathy** [Cadynum/Apelsin#7]
Could you add the clan Creatures Of War/ CoW|
Our irc is #cofwar
Our web is cofwartrem.ucoz.com
And our server is CoW|bot server

Tanx,
Rathy

**Comment by Cadynum** [comment]
Clans are added dynamically so no code change is required.
Your clan is now added. If you want to change something clan-related in the future mail it to clans@ddos-tremulous.eu
